# -*- coding: utf-8 -*-
"""part2_order_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kyJLlppWi2xWTdUBuZuzGLBB4eQ-nih
"""

import copy

# ================= DATA =================

menu = {
    "Paneer Tikka":   {"category": "Starters",  "price": 180.0, "available": True},
    "Chicken Wings":  {"category": "Starters",  "price": 220.0, "available": False},
    "Veg Soup":       {"category": "Starters",  "price": 120.0, "available": True},
    "Butter Chicken": {"category": "Mains",     "price": 320.0, "available": True},
    "Dal Tadka":      {"category": "Mains",     "price": 180.0, "available": True},
    "Veg Biryani":    {"category": "Mains",     "price": 250.0, "available": True},
    "Garlic Naan":    {"category": "Mains",     "price":  40.0, "available": True},
    "Gulab Jamun":    {"category": "Desserts",  "price":  90.0, "available": True},
    "Rasgulla":       {"category": "Desserts",  "price":  80.0, "available": True},
    "Ice Cream":      {"category": "Desserts",  "price": 110.0, "available": False},
}

inventory = {
    "Paneer Tikka":   {"stock": 10, "reorder_level": 3},
    "Chicken Wings":  {"stock":  8, "reorder_level": 2},
    "Veg Soup":       {"stock": 15, "reorder_level": 5},
    "Butter Chicken": {"stock": 12, "reorder_level": 4},
    "Dal Tadka":      {"stock": 20, "reorder_level": 5},
    "Veg Biryani":    {"stock":  6, "reorder_level": 3},
    "Garlic Naan":    {"stock": 30, "reorder_level": 10},
    "Gulab Jamun":    {"stock":  5, "reorder_level": 2},
    "Rasgulla":       {"stock":  4, "reorder_level": 3},
    "Ice Cream":      {"stock":  7, "reorder_level": 4},
}

sales_log = {
    "2025-01-01": [
        {"order_id": 1,  "items": ["Paneer Tikka", "Garlic Naan"], "total": 220.0},
        {"order_id": 2,  "items": ["Gulab Jamun", "Veg Soup"], "total": 210.0},
        {"order_id": 3,  "items": ["Butter Chicken", "Garlic Naan"], "total": 360.0},
    ],
    "2025-01-02": [
        {"order_id": 4,  "items": ["Dal Tadka", "Garlic Naan"], "total": 220.0},
        {"order_id": 5,  "items": ["Veg Biryani", "Gulab Jamun"], "total": 340.0},
    ],
    "2025-01-03": [
        {"order_id": 6,  "items": ["Paneer Tikka", "Rasgulla"], "total": 260.0},
        {"order_id": 7,  "items": ["Butter Chicken", "Veg Biryani"], "total": 570.0},
        {"order_id": 8,  "items": ["Garlic Naan", "Gulab Jamun"], "total": 130.0},
    ],
    "2025-01-04": [
        {"order_id": 9,  "items": ["Dal Tadka", "Garlic Naan", "Rasgulla"], "total": 300.0},
        {"order_id": 10, "items": ["Paneer Tikka", "Gulab Jamun"], "total": 270.0},
    ],
}

# ================= TASK 1 =================

print("\n===== MENU =====")

categories = set([v["category"] for v in menu.values()])

for cat in categories:
    print(f"\n===== {cat} =====")
    for item, details in menu.items():
        if details["category"] == cat:
            status = "Available" if details["available"] else "Unavailable"
            print(f"{item:<18} ₹{details['price']:.2f} [{status}]")

print("\nStats:")
print("Total items:", len(menu))
print("Available items:", sum(1 for v in menu.values() if v["available"]))

most_exp = max(menu, key=lambda x: menu[x]["price"])
print("Most expensive:", most_exp, menu[most_exp]["price"])

print("Under ₹150:")
for item, v in menu.items():
    if v["price"] < 150:
        print(item, v["price"])

# ================= TASK 2 =================

cart = []

def add_item(name, qty):
    if name not in menu:
        print("Item not found:", name)
        return
    if not menu[name]["available"]:
        print("Item unavailable:", name)
        return

    for c in cart:
        if c["item"] == name:
            c["quantity"] += qty
            return

    cart.append({"item": name, "quantity": qty, "price": menu[name]["price"]})

def remove_item(name):
    for c in cart:
        if c["item"] == name:
            cart.remove(c)
            return
    print("Not in cart:", name)

def show_cart():
    print("\nCart:")
    for c in cart:
        print(c)

add_item("Paneer Tikka", 2)
show_cart()

add_item("Gulab Jamun", 1)
show_cart()

add_item("Paneer Tikka", 1)
show_cart()

add_item("Mystery Burger", 1)
add_item("Chicken Wings", 1)

remove_item("Gulab Jamun")
show_cart()

print("\n===== ORDER SUMMARY =====")
subtotal = sum(c["quantity"] * c["price"] for c in cart)

for c in cart:
    print(f"{c['item']} x{c['quantity']} ₹{c['quantity']*c['price']}")

gst = subtotal * 0.05
total = subtotal + gst

print("Subtotal:", subtotal)
print("GST:", round(gst, 2))
print("Total:", round(total, 2))

# ================= TASK 3 =================

inventory_backup = copy.deepcopy(inventory)

inventory["Paneer Tikka"]["stock"] = 99

print("\nCheck deep copy:")
print("Inventory:", inventory["Paneer Tikka"]["stock"])
print("Backup:", inventory_backup["Paneer Tikka"]["stock"])

inventory = copy.deepcopy(inventory_backup)

for c in cart:
    item = c["item"]
    qty = c["quantity"]

    if inventory[item]["stock"] >= qty:
        inventory[item]["stock"] -= qty
    else:
        print("Low stock for", item)
        inventory[item]["stock"] = 0

print("\nReorder Alerts:")
for item, v in inventory.items():
    if v["stock"] <= v["reorder_level"]:
        print("⚠", item, v["stock"])

# ================= TASK 4 =================

def revenue(log):
    d = {}
    for date, orders in log.items():
        d[date] = sum(o["total"] for o in orders)
    return d

rev = revenue(sales_log)

print("\nRevenue per day:")
for k, v in rev.items():
    print(k, v)

best = max(rev, key=rev.get)
print("Best day:", best)

# most ordered item
count = {}
for orders in sales_log.values():
    for o in orders:
        for item in o["items"]:
            count[item] = count.get(item, 0) + 1

print("Most ordered:", max(count, key=count.get))

# add new day
sales_log["2025-01-05"] = [
    {"order_id": 11, "items": ["Butter Chicken", "Gulab Jamun", "Garlic Naan"], "total": 490.0},
    {"order_id": 12, "items": ["Paneer Tikka", "Rasgulla"], "total": 260.0},
]

print("\nUpdated revenue:")
rev = revenue(sales_log)
for k, v in rev.items():
    print(k, v)

print("Best day:", max(rev, key=rev.get))

# enumerate orders
print("\nAll Orders:")
all_orders = []
for date, orders in sales_log.items():
    for o in orders:
        all_orders.append((date, o))

for i, (date, o) in enumerate(all_orders, 1):
    print(f"{i}. [{date}] Order #{o['order_id']} ₹{o['total']} Items: {', '.join(o['items'])}")