# -*- coding: utf-8 -*-
"""part4_visualization_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-FaMeKNZPLsmG9r070HMrWUosDg0dA6
"""

# If needed in Colab, uncomment:
# !pip install pandas matplotlib seaborn scikit-learn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from io import StringIO

# =========================================
# CREATE students.csv
# =========================================
csv_data = """name,math,science,english,history,pe,attendance_pct,study_hours_per_day,passed
Alice,88,92,76,80,95,92,4.5,1
Bob,42,55,48,50,60,65,1.2,0
Charlie,75,70,80,68,88,85,3.0,1
Diana,95,98,91,89,97,98,6.0,1
Eve,38,42,50,45,55,58,0.8,0
Frank,60,65,72,58,70,78,2.5,1
Grace,55,48,44,52,62,60,1.5,0
Henry,82,79,85,77,90,88,4.0,1
Iris,70,74,68,65,78,80,3.5,1
Jack,30,35,40,28,45,50,0.5,0
Karen,65,60,70,62,75,72,2.8,1
Liam,48,52,44,55,58,62,1.8,0
Mia,91,94,88,92,96,95,5.5,1
Noah,58,62,55,60,68,70,2.0,0
Olivia,78,75,82,70,85,84,3.8,1
"""

with open("students.csv", "w", encoding="utf-8") as file:
    file.write(csv_data)

# =========================================
# LOAD DATA
# =========================================
df = pd.read_csv("students.csv")
subject_cols = ['math', 'science', 'english', 'history', 'pe']
df['avg_score'] = df[subject_cols].mean(axis=1)

# =========================================
# TASK 1 — DATA EXPLORATION WITH PANDAS
# =========================================
print("=" * 60)
print("TASK 1 — DATA EXPLORATION WITH PANDAS")
print("=" * 60)

print("\nFirst 5 rows:")
print(df.head())

print("\nShape of dataset:")
print(df.shape)

print("\nData types:")
print(df.dtypes)

print("\nSummary statistics:")
print(df.describe())

print("\nPassed / Failed counts:")
print(df['passed'].value_counts())

passing_avg = df[df['passed'] == 1][subject_cols].mean()
failing_avg = df[df['passed'] == 0][subject_cols].mean()

print("\nAverage subject scores for passing students:")
print(passing_avg)

print("\nAverage subject scores for failing students:")
print(failing_avg)

df['overall_average'] = df[subject_cols].mean(axis=1)
top_student = df.loc[df['overall_average'].idxmax()]

print("\nStudent with the highest overall average:")
print(top_student[['name', 'overall_average']])

# =========================================
# TASK 2 — DATA VISUALIZATION WITH MATPLOTLIB
# =========================================
print("\n" + "=" * 60)
print("TASK 2 — DATA VISUALIZATION WITH MATPLOTLIB")
print("=" * 60)

# Plot 1 — Bar chart
plt.figure(figsize=(8, 5))
subject_means = df[subject_cols].mean()
plt.bar(subject_means.index, subject_means.values)
plt.title("Average Score per Subject Across All Students")
plt.xlabel("Subject")
plt.ylabel("Average Score")
plt.tight_layout()
plt.savefig("plot1_bar.png")
plt.show()

# Plot 2 — Histogram
plt.figure(figsize=(8, 5))
plt.hist(df['math'], bins=5, edgecolor='black')
math_mean = df['math'].mean()
plt.axvline(math_mean, linestyle='--', label=f"Mean = {math_mean:.2f}")
plt.title("Distribution of Math Scores")
plt.xlabel("Math Score")
plt.ylabel("Frequency")
plt.legend()
plt.tight_layout()
plt.savefig("plot2_histogram.png")
plt.show()

# Plot 3 — Scatter plot
plt.figure(figsize=(8, 5))
pass_group = df[df['passed'] == 1]
fail_group = df[df['passed'] == 0]

plt.scatter(pass_group['study_hours_per_day'], pass_group['avg_score'], label='Pass')
plt.scatter(fail_group['study_hours_per_day'], fail_group['avg_score'], label='Fail')

plt.title("Study Hours per Day vs Average Score")
plt.xlabel("Study Hours per Day")
plt.ylabel("Average Score")
plt.legend()
plt.tight_layout()
plt.savefig("plot3_scatter.png")
plt.show()

# Plot 4 — Box plot
plt.figure(figsize=(8, 5))
pass_attendance = df[df['passed'] == 1]['attendance_pct'].tolist()
fail_attendance = df[df['passed'] == 0]['attendance_pct'].tolist()

plt.boxplot([pass_attendance, fail_attendance], labels=['Pass', 'Fail'])
plt.title("Attendance Percentage: Pass vs Fail")
plt.xlabel("Result")
plt.ylabel("Attendance Percentage")
plt.tight_layout()
plt.savefig("plot4_box.png")
plt.show()

# Plot 5 — Line plot
plt.figure(figsize=(10, 5))
plt.plot(df['name'], df['math'], marker='o', linestyle='-', label='Math')
plt.plot(df['name'], df['science'], marker='s', linestyle='--', label='Science')
plt.title("Math and Science Scores for Each Student")
plt.xlabel("Student Name")
plt.ylabel("Score")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.savefig("plot5_line.png")
plt.show()

# =========================================
# TASK 3 — DATA VISUALIZATION WITH SEABORN
# =========================================
print("\n" + "=" * 60)
print("TASK 3 — DATA VISUALIZATION WITH SEABORN")
print("=" * 60)

# Seaborn bar plots
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.barplot(data=df, x='passed', y='math', ax=axes[0])
axes[0].set_title("Average Math Score by Pass/Fail")
axes[0].set_xlabel("Passed")
axes[0].set_ylabel("Average Math Score")
axes[0].set_xticklabels(['Fail', 'Pass'])

sns.barplot(data=df, x='passed', y='science', ax=axes[1])
axes[1].set_title("Average Science Score by Pass/Fail")
axes[1].set_xlabel("Passed")
axes[1].set_ylabel("Average Science Score")
axes[1].set_xticklabels(['Fail', 'Pass'])

plt.tight_layout()
plt.savefig("plot6_seaborn_bar.png")
plt.show()

# Seaborn scatter + regression
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='attendance_pct', y='avg_score', hue='passed')
sns.regplot(data=df[df['passed'] == 1], x='attendance_pct', y='avg_score', scatter=False, label='Pass')
sns.regplot(data=df[df['passed'] == 0], x='attendance_pct', y='avg_score', scatter=False, label='Fail')

plt.title("Attendance Percentage vs Average Score")
plt.xlabel("Attendance Percentage")
plt.ylabel("Average Score")
plt.legend()
plt.tight_layout()
plt.savefig("plot7_seaborn_scatter.png")
plt.show()

# Comparison comment:
# Matplotlib gave more manual control over each plot and made the step-by-step logic very clear.
# Seaborn was faster for attractive statistical plots, especially for grouped bar plots and regression lines.
# But Seaborn still depended on Matplotlib for figure handling, sizing, saving, and final customization.

# =========================================
# TASK 4 — MACHINE LEARNING WITH SCIKIT-LEARN
# =========================================
print("\n" + "=" * 60)
print("TASK 4 — MACHINE LEARNING WITH SCIKIT-LEARN")
print("=" * 60)

feature_cols = ['math', 'science', 'english', 'history', 'pe', 'attendance_pct', 'study_hours_per_day']
X = df[feature_cols]
y = df['passed']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

train_preds = model.predict(X_train_scaled)
train_accuracy = accuracy_score(y_train, train_preds)
print("\nTraining accuracy:", train_accuracy)

test_preds = model.predict(X_test_scaled)
test_accuracy = accuracy_score(y_test, test_preds)
print("Test accuracy:", test_accuracy)

print("\nTest set predictions:")
test_names = df.loc[X_test.index, 'name']

for name, actual, predicted in zip(test_names, y_test, test_preds):
    status = "✅ correct" if actual == predicted else "❌ wrong"
    print(f"{name}: actual = {actual}, predicted = {predicted} -> {status}")

coefficients = model.coef_[0]
feature_importance = list(zip(feature_cols, coefficients))
feature_importance_sorted = sorted(feature_importance, key=lambda x: abs(x[1]), reverse=True)

print("\nFeature coefficients sorted by absolute value:")
for feature, coef in feature_importance_sorted:
    print(f"{feature}: {coef:.4f}")

# Horizontal bar chart of coefficients
sorted_features = [item[0] for item in feature_importance_sorted]
sorted_coefs = [item[1] for item in feature_importance_sorted]
colors = ['green' if coef > 0 else 'red' for coef in sorted_coefs]

plt.figure(figsize=(10, 5))
plt.barh(sorted_features, sorted_coefs, color=colors)
plt.title("Feature Coefficients from Logistic Regression")
plt.xlabel("Coefficient Value")
plt.ylabel("Feature")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("plot8_feature_coefficients.png")
plt.show()

# Bonus — Predict for a new student
new_student = [[75, 70, 68, 65, 80, 82, 3.2]]
new_student_scaled = scaler.transform(new_student)
new_prediction = model.predict(new_student_scaled)[0]
new_probability = model.predict_proba(new_student_scaled)[0]

print("\nBonus — New student prediction:")
if new_prediction == 1:
    print("Predicted result: Pass")
else:
    print("Predicted result: Fail")

print(f"Probability of Fail: {new_probability[0]:.4f}")
print(f"Probability of Pass: {new_probability[1]:.4f}")

# =========================================
# SHOW FILES CREATED
# =========================================
print("\nFiles created:")
print("students.csv")
print("plot1_bar.png")
print("plot2_histogram.png")
print("plot3_scatter.png")
print("plot4_box.png")
print("plot5_line.png")
print("plot6_seaborn_bar.png")
print("plot7_seaborn_scatter.png")
print("plot8_feature_coefficients.png")