# -*- coding: utf-8 -*-
"""part3_api_files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cN5VOQo-W4XLlzpmHSMQJ0Aua8FL-cRG
"""

# ==============================
# PART 3: File I/O, APIs & Exception Handling
# Theme: Product Explorer & Error-Resilient Logger
# ==============================

import requests
from datetime import datetime

# ------------------------------
# LOGGER FUNCTION
# ------------------------------
def log_error(function_name, error_type, message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] ERROR in {function_name}: {error_type} — {message}\n"
    with open("error_log.txt", "a", encoding="utf-8") as file:
        file.write(log_entry)


# ==============================
# TASK 1 — FILE READ & WRITE BASICS
# ==============================

print("=" * 60)
print("TASK 1 — FILE READ & WRITE BASICS")
print("=" * 60)

notes_lines = [
    "Topic 1: Variables store data. Python is dynamically typed.\n",
    "Topic 2: Lists are ordered and mutable.\n",
    "Topic 3: Dictionaries store key-value pairs.\n",
    "Topic 4: Loops automate repetitive tasks.\n",
    "Topic 5: Exception handling prevents crashes.\n"
]

# Part A — Write
with open("python_notes.txt", "w", encoding="utf-8") as file:
    file.writelines(notes_lines)
print("File written successfully.")

extra_lines = [
    "Topic 6: Functions help organise code into reusable blocks.\n",
    "Topic 7: APIs allow programs to communicate with external services.\n"
]

with open("python_notes.txt", "a", encoding="utf-8") as file:
    file.writelines(extra_lines)
print("Lines appended.")

# Part B — Read
with open("python_notes.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

print("\nContents of python_notes.txt:")
for index, line in enumerate(lines, start=1):
    print(f"{index}. {line.strip()}")

print(f"\nTotal number of lines in the file: {len(lines)}")

keyword = input("\nEnter a keyword to search in the notes: ").strip().lower()

matches = []
for line in lines:
    if keyword in line.lower():
        matches.append(line.strip())

print("\nSearch Results:")
if matches:
    for match in matches:
        print(match)
else:
    print("No lines found containing that keyword.")


# ==============================
# TASK 2 — API INTEGRATION
# ==============================

print("\n" + "=" * 60)
print("TASK 2 — API INTEGRATION")
print("=" * 60)

BASE_URL = "https://dummyjson.com/products"

def fetch_products():
    url = f"{BASE_URL}?limit=20"
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            data = response.json()
            return data["products"]
        else:
            print(f"Failed to fetch products. Status code: {response.status_code}")
            log_error("fetch_products", "HTTPError", f"Status code {response.status_code}")
            return []
    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")
        log_error("fetch_products", "ConnectionError", "No internet or server unreachable")
        return []
    except requests.exceptions.Timeout:
        print("Request timed out. Try again later.")
        log_error("fetch_products", "Timeout", "The request took too long")
        return []
    except Exception as e:
        print(f"Unexpected error: {e}")
        log_error("fetch_products", type(e).__name__, str(e))
        return []

products = fetch_products()

# Step 1 — Fetch and Display Products
if products:
    print("\nFetched Products:")
    print(f"{'ID':<5} {'Title':<30} {'Category':<20} {'Price':<10} {'Rating':<10}")
    print("-" * 80)
    for product in products:
        print(f"{product['id']:<5} {product['title']:<30} {product['category']:<20} ${product['price']:<9} {product['rating']:<10}")

# Step 2 — Filter and Sort
filtered_products = []
for product in products:
    if product["rating"] >= 4.5:
        filtered_products.append(product)

filtered_products.sort(key=lambda x: x["price"], reverse=True)

print("\nProducts with rating >= 4.5, sorted by price (descending):")
if filtered_products:
    print(f"{'ID':<5} {'Title':<30} {'Category':<20} {'Price':<10} {'Rating':<10}")
    print("-" * 80)
    for product in filtered_products:
        print(f"{product['id']:<5} {product['title']:<30} {product['category']:<20} ${product['price']:<9} {product['rating']:<10}")
else:
    print("No products found with rating >= 4.5")

# Step 3 — Search by Category
def fetch_laptops():
    url = f"{BASE_URL}/category/laptops"
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            data = response.json()
            return data["products"]
        else:
            print(f"Failed to fetch laptops. Status code: {response.status_code}")
            log_error("fetch_laptops", "HTTPError", f"Status code {response.status_code}")
            return []
    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")
        log_error("fetch_laptops", "ConnectionError", "No internet or server unreachable")
        return []
    except requests.exceptions.Timeout:
        print("Request timed out. Try again later.")
        log_error("fetch_laptops", "Timeout", "The request took too long")
        return []
    except Exception as e:
        print(f"Unexpected error: {e}")
        log_error("fetch_laptops", type(e).__name__, str(e))
        return []

laptops = fetch_laptops()

print("\nLaptops Category Products:")
if laptops:
    for laptop in laptops:
        print(f"{laptop['title']} — ${laptop['price']}")
else:
    print("No laptop products found.")

# Step 4 — POST Request (Simulated)
def add_product():
    url = f"{BASE_URL}/add"
    payload = {
        "title": "My Custom Product",
        "price": 999,
        "category": "electronics",
        "description": "A product I created via API"
    }

    try:
        response = requests.post(url, json=payload, timeout=5)
        if response.status_code in [200, 201]:
            print("\nPOST Response:")
            print(response.json())
        else:
            print(f"POST request failed. Status code: {response.status_code}")
            log_error("add_product", "HTTPError", f"Status code {response.status_code}")
    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")
        log_error("add_product", "ConnectionError", "No internet or server unreachable")
    except requests.exceptions.Timeout:
        print("Request timed out. Try again later.")
        log_error("add_product", "Timeout", "The request took too long")
    except Exception as e:
        print(f"Unexpected error: {e}")
        log_error("add_product", type(e).__name__, str(e))

add_product()


# ==============================
# TASK 3 — EXCEPTION HANDLING
# ==============================

print("\n" + "=" * 60)
print("TASK 3 — EXCEPTION HANDLING")
print("=" * 60)

# Part A — Guarded Calculator
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return "Error: Cannot divide by zero"
    except TypeError:
        return "Error: Invalid input types"

print("\nTesting safe_divide:")
print("safe_divide(10, 2) =", safe_divide(10, 2))
print("safe_divide(10, 0) =", safe_divide(10, 0))
print('safe_divide("ten", 2) =', safe_divide("ten", 2))


# Part B — Guarded File Reader
def read_file_safe(filename):
    try:
        with open(filename, "r", encoding="utf-8") as file:
            content = file.read()
            return content
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
    finally:
        print("File operation attempt complete.")

print("\nReading python_notes.txt:")
content1 = read_file_safe("python_notes.txt")
if content1:
    print(content1)

print("\nReading ghost_file.txt:")
content2 = read_file_safe("ghost_file.txt")
if content2:
    print(content2)


# Part C — Robust API Calls
def make_safe_get_request(url, function_name):
    try:
        response = requests.get(url, timeout=5)
        return response
    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")
        log_error(function_name, "ConnectionError", "No internet or server unreachable")
    except requests.exceptions.Timeout:
        print("Request timed out. Try again later.")
        log_error(function_name, "Timeout", "The request took too long")
    except Exception as e:
        print(f"Unexpected error: {e}")
        log_error(function_name, type(e).__name__, str(e))
    return None

def make_safe_post_request(url, payload, function_name):
    try:
        response = requests.post(url, json=payload, timeout=5)
        return response
    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")
        log_error(function_name, "ConnectionError", "No internet or server unreachable")
    except requests.exceptions.Timeout:
        print("Request timed out. Try again later.")
        log_error(function_name, "Timeout", "The request took too long")
    except Exception as e:
        print(f"Unexpected error: {e}")
        log_error(function_name, type(e).__name__, str(e))
    return None


# Part D — Input Validation Loop
print("\nProduct Lookup")
while True:
    user_input = input("Enter a product ID to look up (1–100), or 'quit' to exit: ").strip()

    if user_input.lower() == "quit":
        print("Exiting product lookup.")
        break

    if not user_input.isdigit():
        print("Invalid input. Please enter a whole number between 1 and 100.")
        continue

    product_id = int(user_input)

    if product_id < 1 or product_id > 100:
        print("Invalid input. Product ID must be between 1 and 100.")
        continue

    url = f"{BASE_URL}/{product_id}"
    response = make_safe_get_request(url, "lookup_product")

    if response:
        if response.status_code == 404:
            print("Product not found.")
            log_error("lookup_product", "HTTPError", f"404 Not Found for product ID {product_id}")
        elif response.status_code == 200:
            product_data = response.json()
            print(f"Title: {product_data['title']}")
            print(f"Price: ${product_data['price']}")
        else:
            print(f"Unexpected status code: {response.status_code}")
            log_error("lookup_product", "HTTPError", f"Status code {response.status_code} for product ID {product_id}")


# ==============================
# TASK 4 — LOGGING TO FILE
# ==============================

print("\n" + "=" * 60)
print("TASK 4 — LOGGING TO FILE")
print("=" * 60)

# Intentionally trigger ConnectionError
try:
    bad_url = "https://this-host-does-not-exist-xyz.com/api"
    requests.get(bad_url, timeout=5)
except requests.exceptions.ConnectionError as e:
    print("Intentional ConnectionError triggered and logged.")
    log_error("fetch_bad_url", "ConnectionError", str(e))
except requests.exceptions.Timeout as e:
    print("Intentional timeout triggered and logged.")
    log_error("fetch_bad_url", "Timeout", str(e))
except Exception as e:
    print(f"Unexpected error: {e}")
    log_error("fetch_bad_url", type(e).__name__, str(e))

# Intentionally trigger HTTP 404
response_404 = make_safe_get_request("https://dummyjson.com/products/999", "lookup_product_999")
if response_404:
    if response_404.status_code != 200:
        print("Intentional HTTP error triggered and logged.")
        log_error("lookup_product_999", "HTTPError", "404 Not Found for product ID 999")

# Read and print error_log.txt
print("\nContents of error_log.txt:")
try:
    with open("error_log.txt", "r", encoding="utf-8") as file:
        print(file.read())
except FileNotFoundError:
    print("error_log.txt was not found.")